---
title: "Informe Telecomunicaciones 1"
output: 
  pagedown::html_paged:
    css: 
    - "style/sgdf.css"
    - "style/custom-page_sgdf.css"

#knit: pagedown::chrome_print
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE,
	dpi = 300,
	fig.width = 7, 
  fig.height = 3.5,
	out.width = 2100
)
```

```{r packages}
library(tidyverse)
library(gt)
```


```{r theme}


# définir un scale
vect_col4 <- c("#ff8300", "#0077b3", "#d03f15", "#007254")
vect_col5 <- c("#ff8300", "#0077b3", "#d03f15", "#007254", "#65bc99")
vect_col8 <- c("#003a5d", "#ff8300", "#0077b3", "#d03f15", "#007254", "#65bc99", "#6e74aa", "#003a5d")

options(scipen = 10000)

source("../common.R")

FECHA_INFORME_ANUAL <-  as.Date("2020-12-01")
FECHA_TITULO_STOCK <-  "Diciembre 2020"
FECHA_TITULO_FLUJO <-  "año 2020"



```


```{r child = '01-fija.Rmd'}


```


```{r child = '02-ldi.Rmd'}
```



```{r child = '03-banda_ancha.Rmd'}
```


```{r child = '04-radiobases.Rmd'}
```

```{r child = '05-cobertura.Rmd'}
```



```{r child = '06-datos_moviles_servicios.Rmd'}
```


```{r child = '07-mensajes.Rmd'}
```


```{r child = '08-voz.Rmd'}
```


```{r child = '09-roaming.Rmd'}
```


<!-- ```{r child = '10-abonados.Rmd'} -->
<!-- ``` -->


