---
title: "Informe de mercado de servicios de Telecomunicaciones de Uruguay"
output:
  word_document:
    reference_docx: word_report.docx
graphics: yes
---
```{r, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      fig.width = 10, 
                      fig.height = 5.5)

library(officedown)
library(officer)
library(tidyverse)

options(scipen = 10000)

theme_set(theme_minimal() + 
            theme(plot.background = element_rect(fill = "#EEEEEE",
                                                 color = "white"),
                  axis.title = element_text(size = rel(1.5)),
                  axis.text = element_text(size = rel(1.5)),
                  axis.line.x = element_blank(),
                  axis.ticks = element_blank()))


```


<!-- ```{r child = '1-pib-telecom.Rmd'} -->
<!-- ``` -->

<!---BLOCK_TOC{level: 1}--->


```{r child = '1-fija.Rmd'}
```



```{r child = '2-ldi.Rmd'}
```



<!-- ```{r child = '5-datos-internet.Rmd'} -->
<!-- ``` -->


<!-- ```{r child = '6-01-radiobases.Rmd'} -->
<!-- ``` -->

<!-- ```{r child = '6-02-cobertura.Rmd'} -->
<!-- ``` -->

<!-- ```{r child = '6-03-servicios.Rmd'} -->
<!-- ``` -->


<!-- ```{r child = '6-04-moviles-datos.Rmd'} -->
<!-- ``` -->


<!-- ```{r child = '6-05-mensajes.Rmd'} -->
<!-- ``` -->


<!-- ```{r child = '6-06-voz.Rmd'} -->
<!-- ``` -->


<!-- ```{r child = '6-07-roaming.Rmd'} -->
<!-- ``` -->


<!-- ```{r child = '7-abonados.Rmd'} -->
<!-- ``` -->

