---
output:
  word_document:
    reference_docx: word_report.docx
graphics: yes
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message = FALSE)

options(scipen = 10000)



# Theme
source('../common.R')

cobertura <- import_cobertura()


month_label <- function(x) {
  y <- as_date(x)
  glue::glue("{month(x)}/{format(y, '%y')}")
}


```



## 82. Cobertura territorial nacional (%) por tecnología (`r FECHA_TITULO_STOCK`)

```{r}
tabla_102 <- cobertura %>% 
  filter(fecha == FECHA_INFORME_SEMESTRAL) %>% 
  filter(depto == "País") %>% 
  group_by(tipo) %>% 
  summarize(cobertura = max(val, na.rm = TRUE))

tabla_102 %>%
  ggplot(aes(factor(tipo), cobertura)) +
  geom_col(fill = pal[5], width = 0.5) + 
  geom_text(aes(label=percent_format(
    big.mark=".",
    decimal.mark = ".",
    accuracy=0.5,
    scale = 1)(cobertura)), 
            nudge_y = 7) +
  scale_x_discrete(expand = expand_scale(add = c(0.5, 0.5),
                                         mult = c(0, 0))) +
  scale_y_continuous(breaks = NULL) +
  geom_hline(yintercept = 0) +
  labs(x="", y="")
```


## 84. Cobertura territorial GSM (%) por departamento (`r FECHA_TITULO_STOCK`)

```{r}
tabla_104 <- cobertura %>% 
  filter(fecha == FECHA_INFORME_SEMESTRAL) %>% 
  filter(tipo == "GSM") %>% 
  filter(depto != "País") %>% 
  group_by(depto) %>% 
  summarize(cobertura = max(val, na.rm = TRUE))

tabla_104 %>% 
  ggplot(aes(fct_reorder(depto, cobertura), cobertura)) +
  geom_col(fill = pal[5], width = 0.5) + 
  geom_text(aes(label=percent_format(big.mark=".", 
                                     decimal.mark = ",",
                                     accuracy = .1,
                                     scale = 1)(cobertura)), 
            nudge_y = 7) +
  scale_x_discrete(expand = expand_scale(add = c(0.5, 0.5),
                                         mult = c(0, 0))) +
  scale_y_continuous(breaks = NULL) +
  geom_hline(yintercept = 0) +
  labs(x="", y="") +
  coord_flip()
```



## 86. Cobertura territorial 3G (%) por departamento (`r FECHA_TITULO_STOCK`)

```{r}
tabla_106 <- cobertura %>% 
  filter(fecha == FECHA_INFORME_SEMESTRAL) %>% 
  filter(tipo == "3G") %>% 
  filter(depto != "País") %>% 
  group_by(depto) %>% 
  summarize(cobertura = max(val, na.rm = TRUE))

tabla_106 %>% 
  ggplot(aes(fct_reorder(depto, cobertura), cobertura)) +
  geom_col(fill = pal[5], width = 0.5) + 
  geom_text(aes(label=percent_format(big.mark=".",
                                     accuracy=.1,
                                     scale = 1)(cobertura)), 
            nudge_y = 7) +
  scale_x_discrete(expand = expand_scale(add = c(0.5, 0.5),
                                         mult = c(0, 0))) +
  scale_y_continuous(breaks = NULL) +
  geom_hline(yintercept = 0) +
  labs(x="", y="") +
  coord_flip()
```


## 88. Cobertura territorial LTE (%) por departamento (`r FECHA_TITULO_STOCK`)

```{r}
tabla_108 <- cobertura %>% 
  filter(fecha == FECHA_INFORME_SEMESTRAL) %>% 
  filter(tipo == "LTE") %>% 
  filter(depto != "País") %>% 
  group_by(depto) %>% 
  summarize(cobertura = max(val, na.rm = TRUE))

tabla_108 %>% 
  ggplot(aes(fct_reorder(depto, cobertura), cobertura)) +
  geom_col(fill = pal[5], width = 0.5) + 
  geom_text(aes(label=percent_format(big.mark=".", 
                                     accuracy=.1,
                                     scale = 1)(cobertura)), 
            nudge_y = 8) +
  scale_x_discrete(expand = expand_scale(add = c(0.5, 0.5),
                                         mult = c(0, 0))) +
  scale_y_continuous(breaks = NULL) +
  geom_hline(yintercept = 0) +
  labs(x="", y="") +
  coord_flip()

```






